---
- hosts: all
  name: Add cis-91 packages
  become: yes
  tasks:
    - name: Install packages 
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        name:
          - php 
          - php-xml
          - apache2

    - name: Download Dokuwiki
      ansible.builtin.get_url:
        url: https://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz
        dest: /tmp/
        mode: '0755'

