---
- hosts: all
  name: Add cis-91 packages and disk mount points
  become: true
  tasks:
    - name: Install packages 
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        name:
          - python3-pip 
          - python3-venv
          - nginx

    - name: Create an ext4 filesystem for lab09 persistent_disk
      community.general.filesystem:
        fstype: ext4
        dev: /dev/disk/by-id/google-lab09-persistent

    
    - name: Create an ext4 filesystem for lab09 scratch_disk
      community.general.filesystem:
        fstype: ext4
        dev: /dev/disk/by-id/google-local-ssd-0

    - name: Mount lab09 attached_disk
      ansible.posix.mount:
        path: /data
        src: /dev/disk/by-id/google-lab09-persistent
        fstype: ext4
        state: mounted

    - name: Mount lab09 scratch_disk
      ansible.posix.mount:
        path: /scratch
        src: /dev/disk/by-id/google-local-ssd-0
        fstype: ext4
        state: mounted

...
